YEAR: 2024
DEFAULT_TEMPLATE: main.html

# TERRITORIOS DISPONIBLES: AND, ARA, AST, BAL, CAN, CAT, CYL, EUS, GAL, LRI, MAD, MUR, NAV, VAL
# DEJAR VACÍO PARA GENERAR TODOS LOS TERRITORIOS
TERRITORIOS:

# IDIOMAS DISPONIBLES: CAS, CAT, EUS, GAL
# DEJAR VACÍO PARA GENERAR TODOS LOS IDIOMAS (SEGÚN TERRITORIO)
IDIOMAS: