YEAR: 2025
DIRECTORIO_INFOGRAFIAS: data
ARCHIVOS_INFOGRAFIAS: datos_entidades.csv, datos_autonomas.csv

# TERRITORIOS DISPONIBLES: AND, ARA, AST, BAL, CAN, CAT, CLM, CYL, EUS, GAL, LRI, MAD, MUR, NAV, VAL
# DEJAR VACÍO PARA GENERAR TODOS LOS TERRITORIOS
TERRITORIOS: NAV

# IDIOMAS DISPONIBLES: CAS, CAT, EUS, GAL
# DEJAR VACÍO PARA GENERAR TODOS LOS IDIOMAS (SEGÚN TERRITORIO)
IDIOMAS: EUS

# Ubicación de pngquant
PNGQUANT_PATH: /usr/bin/pngquant

HTML_PATH: infografias/html
PNG_PATH: infografias/png
PDF_PATH: infografias/pdf